UPDATE `sconfig` SET `svalue`='250' WHERE `soption`='img_max_width';
UPDATE `sconfig` SET `svalue`='130' WHERE `soption`='img_max_height';
INSERT INTO `config` (`config_name`, `config_value`) VALUES ('youtube_api_key', '');
UPDATE `sconfig` SET `svalue` = '3.0' WHERE `soption` = 'version';
INSERT INTO `config` (`config_name`, `config_value`) VALUES('user_photo_width', '120');
INSERT INTO `config` (`config_name`, `config_value`) VALUES('user_photo_height', '190');
INSERT INTO `config` (`config_name`, `config_value`) VALUES('user_avatar_width', '50');
INSERT INTO `config` (`config_name`, `config_value`) VALUES('user_avatar_height', '40');
INSERT INTO `config` (`config_name`, `config_value`) VALUES('recaptcha_sitekey', '');
INSERT INTO `config` (`config_name`, `config_value`) VALUES('recaptcha_secretkey', '');
